site_name: Code42 Developer Portal
site_url: https://developer.code42.com

theme:
    name: material
    favicon: images/favicon.ico
    logo: images/logo_developers.svg
    features:
        - navigation.sections
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.instant
        - navigation.tracking
        - content.code.annotate
    palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: code42/incydr_python
repo_url: https://github.com/code42/incydr_python
edit_uri: ""

nav:
  - Introduction: 'index.md'
  - API Reference: 'api/index.html'
  - SDK:
    - Introduction: 'sdk/index.md'
    - Client: 'sdk/client.md'
    - Settings:
        - Configuration: 'sdk/settings.md'
        - Logging: 'sdk/logging.md'
    - Reference:
      - Alerts: 'sdk/clients/alerts.md'
      - Alert Rules: 'sdk/clients/alert_rules.md'
      - Alert Querying: 'sdk/clients/alert_queries.md'
      - Audit Log: 'sdk/clients/audit_log.md'
      - Cases: 'sdk/clients/cases.md'
      - Customer: 'sdk/clients/customer.md'
      - Departments: 'sdk/clients/departments.md'
      - Devices: 'sdk/clients/devices.md'
      - Directory Groups: 'sdk/clients/directory_groups.md'
      - File Events: 'sdk/clients/file_events.md'
      - File Event Querying: 'sdk/clients/file_event_queries.md'
      - Trusted Activites: 'sdk/clients/trusted_activities.md'
      - Users: 'sdk/clients/users.md'
      - User Risk Profiles: 'sdk/clients/user_risk_profiles.md'
      - Watchlists: 'sdk/clients/watchlists.md'
    - Enums: 'sdk/enums.md'
    - Models: 'sdk/models.md'
  - CLI:
      - Introduction: 'cli/index.md'
      - Getting Started: 'cli/getting_started.md'
      - Bulk Commands: 'cli/bulk.md'
      - Logging: 'cli/logging.md'
      - Migration: 'cli/migration.md'
      - Syslogging: 'cli/syslogging.md'
      - Commands:
        - Alerts: 'cli/cmds/alerts.md'
        - Alert Rules: 'cli/cmds/alert_rules.md'
        - Audit Log: 'cli/cmds/audit_log.md'
        - Cases: 'cli/cmds/cases.md'
        - Departments: 'cli/cmds/departments.md'
        - Devices: 'cli/cmds/devices.md'
        - Directory Groups: 'cli/cmds/directory_groups.md'
        - File Events: 'cli/cmds/file_events.md'
        - Users & Risk Profiles: 'cli/cmds/users.md'
        - Trusted Activites: 'cli/cmds/trusted_activities.md'
        - Watchlists: 'cli/cmds/watchlists.md'
  - Guides:
    - Microsoft Sentinel:
      - Data Collector API: 'guides/azure-sentinel-data-collector.md'
      - Log Analytics Agent: 'guides/azure-sentinel-log-analytics.md'

markdown_extensions:
  - attr_list
  - mkdocs-click
  - pymdownx.critic
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc
  - tables
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
- css/custom.css

plugins:
  - autorefs
  - search
